# Generated by Django 3.2.8 on 2021-10-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(upload_to='media/images'),
        ),
    ]
