# Generated by Django 3.2.8 on 2021-10-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_detail_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='value',
            field=models.TextField(max_length=500),
        ),
    ]
