# Generated by Django 3.2.8 on 2021-11-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_detail_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
