# Generated by Django 3.2.8 on 2021-11-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='sender_id',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
